// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/gb.js', ['gb'], ['gb.Loader']);
goog.addDependency('../../../js/loader.js', ['gb.Loader'], ['goog.dom']);
